### ISSUE TITLE
`d/credentials`: results in segmentation violation

### ISSUE THREAD

**Issue by pradeep17j** [vmware/terraform-provider-vcf#211]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.7.5

### Terraform Provider

v0.10.0

### VMware Cloud Foundation

5.2

### Description

```hcl
data "vcf_credentials" "example" {
}
```

Results in a segmentation fault.

### Affected Resources or Data Sources

vcf_credentials

### Terraform Configuration

```hcl
data "vcf_credentials" "example" {
}
```

### Debug Output

```console
[root@template vcf_creds]# terraform plan
data.vcf_credentials.creds: Reading...
2024-07-30T19:07:23.880-0700 [ERROR] plugin.(*GRPCProvider).ReadDataSource: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-07-30T19:07:23.880-0700 [ERROR] vertex "data.vcf_credentials.creds" error: Plugin did not respond
2024-07-30T19:07:23.880-0700 [ERROR] vertex "data.vcf_credentials.creds (expand)" error: Plugin did not respond

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│   with data.vcf_credentials.creds,
│   on main.tf line 1, in data "vcf_credentials" "creds":
│    1: data "vcf_credentials" "creds" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vcf_v0.10.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xed7466]

goroutine 34 [running]:
github.com/vmware/terraform-provider-vcf/internal/credentials.FlattenCredentials({0xc0006a2200, 0x12, 0x13f22d8?})
        github.com/vmware/terraform-provider-vcf/internal/credentials/credential_operations.go:85 +0x466
github.com/vmware/terraform-provider-vcf/internal/provider.dataCredentialsRead({0x13f2380?, 0xc0003fe1c0?}, 0x0?, {0x1141bc0?, 0xc00021a460?})
        github.com/vmware/terraform-provider-vcf/internal/provider/data_credentials.go:81 +0xa8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000148a80, {0x13f22d8, 0xc000512ed0}, 0xd?, {0x1141bc0, 0xc00021a460})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:823 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000148a80, {0x13f22d8, 0xc000512ed0}, 0xc00039ca80, {0x1141bc0, 0xc00021a460})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1043 +0x149
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000023758, {0x13f22d8?, 0xc000512de0?}, 0xc000512d50)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1434 +0x6c9
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0000ae280, {0x13f22d8?, 0xc0005123c0?}, 0xc000248640)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:688 +0x290
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x121a7c0?, 0xc0000ae280}, {0x13f22d8, 0xc0005123c0}, 0xc00039c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00041e400, {0x13f22d8, 0xc000512300}, {0x13f6e10, 0xc0002c6a80}, 0xc00050c000, 0xc00024c960, 0x1da4dc0, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc00041e400, {0x13f6e10, 0xc0002c6a80}, 0xc00050c000)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 52
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-vcf_v0.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Should have returned credentials of SDDC and BOM components.

### Actual Behavior

Results in a segmentation fault.

### Steps to Reproduce

Run `terraform plan` with following:

```hcl
data "vcf_credentials" "example" {
}
```

**Comment by tenthirtyam** [comment]
PLEASE format your issue content.

**Comment by tenthirtyam** [comment]
@pradeep17j I have updated your issue to reflect the latest 5.x version. The provider is only supported for the versions shown in the `README.md`.

**Please only use generally available versions for public issues.**

**Comment by spacegospod** [comment]
This is not a 5.X-only problem, I managed to reproduce it myself.
The fact that `credentials.FlattenCredentials` was last touched 6 months ago hints that this is not a recent regression.

The bug is due to an attempt to dereference a nil pointer and happens on this line https://github.com/vmware/terraform-provider-vcf/blob/main/internal/credentials/credential_operations.go#L85

The fix should be to simple add sanity checks before attempting to dereference any of the values on the credential resource

**Comment by tenthirtyam** [comment]
Hi @pradeep17j 👋 - 

I have formatted the issue content. We kindly ask that you do the same for future issues.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom
